### ISSUE TITLE
how to get surf

### ISSUE THREAD

**Issue by MajidAbdelilah** [jpbruyere/vkhelpers#12]
in    `VkhPhyInfo* phys = vkh_app_get_phyinfos (e->app, &phyCount, surf);`
how to get surf what function to use to initialize it
thanks for the great work and especially the performance optimizations cant wait to see sse and avx get used

**Comment by jpbruyere** [comment]
For a complete example see: https://github.com/jpbruyere/vkvg/blob/master/tests/common/vkengine.c#L189

**Comment by MajidAbdelilah** [comment]
thanks that is clear
