### ISSUE TITLE
potential bug in vkh_memory_type_from_properties()

### ISSUE THREAD

**Issue by ssmid** [jpbruyere/vkhelpers#17]
https://github.com/jpbruyere/vkhelpers/blob/18059c4c6464ff13ffb6764c8a882cf66d0676f5/src/vkhelpers.c#L289C2-L289C2

This line in vkhelpers.c:vkh_memory_type_from_properties() causes the function to choose the wrong memory_type and my vkvg tests crash. Without it, it's working just fine. I'm not sure what it is supposed to do but it seems wrong here. In the corresponding code from my personal vulkan-hello-triangle (which is mostly taken from vulkan-tutorial.com) it is simply not there and it's also working as intended.

**Comment by jpbruyere** [comment]
Having a quick look into this, I see in https://github.com/KhronosGroup/Vulkan-Samples/blob/main/framework/core/device.cpp#L341 the presence of this bit shift. I double check that and come back to you soon. Thank you for your report.

**Comment by jpbruyere** [comment]
Can you provide the full description of you problem with the current value of the different variables:

- typeBits (when calling the method)
- memFlags
- the details on the choosen memory:  index, propertyFlags, heapIndex
- the details on the expected memory: index, propertyFlags, heapIndex

**Comment by jpbruyere** [comment]
There is effectively a bug here. The memoryTypeBits bitmask from VkMemoryRequirements has one bit set for each memory type index supported for creating resource. So, first step prior testing propertyFlags is to first check if memory index is valid for this kind of resource. The CHECK_BIT macro is enough.

**Comment by jpbruyere** [comment]
Thank you for your bug fix.
