### ISSUE TITLE
phy_info_create_graphic_queues in vma.h

### ISSUE THREAD

**Issue by inzhefop** [jpbruyere/vkhelpers#20]
I think it should be vkh_phy_info_create_graphic_queues(...) because otherwise the function is not implemented.
Position: vma.h l. 191

**Comment by jpbruyere** [comment]
Corrected, thanks. It' on the dev branch (https://github.com/jpbruyere/vkhelpers/commit/0568f11d21885574e1b27865a938da1f40026a51), I will merge to master soon.
